### ISSUE TITLE
yarn build:contract <- docs are out of sync

### ISSUE THREAD

**Issue by dckc** [agoric-labs/dapp-swaparoo#1]
```
~/projects/dapp-swaparoo$ yarn build:contract
yarn run v1.22.19
error Command "build:contract" not found.
```

version I have checked out:
2023-11-17 14:01 9918176 fix: add addr arg to offer.

**Comment by dckc** [comment]
Using `agoric install` seems to suffice to get `yarn test` in the `contract/` directory to work:

```
~/projects/dapp-swaparoo/contract$ yarn test
yarn run v1.22.19
warning package.json: No license field
$ ava --verbose

  - [todo] mis-matched offers
Temporary logging of sent error (Error#1)
  ✔ basic swap (3.5s)
  ✔ Jack Pays (3.5s)
  ✔ Neither Pays (3.6s)
  ✔ re-add Issuers (4.1s)
Error#1: Proposals didn't match, first want: {"Cow":{"brand":"[Alleged: cows brand]","value":"[copyBag]"},"Refund":{"brand":"[Alleged: ZDEFAULT brand]","value":"[1000000n]"}}, second give: {"Cow":{"brand":"[Alleged: cows brand]","value":"[copyBag]"}}
  at secondSeatOfferHandler (.../swaparoo-contract/src/swaparoo.js:103:13)
  at eval (.../pass-style/src/make-far.js:161:31)

Error#1 ERROR_NOTE: Sent as error:anon-marshal#10001
Error#1 ERROR_NOTE: Sent as error:anon-marshal#10002
Temporary logging of sent error (Error#1)
Error#1 ERROR_NOTE: Sent as error:anon-marshal#10003
Temporary logging of sent error (Error#1)
Error#1 ERROR_NOTE: Sent as error:anon-marshal#10004
Temporary logging of sent error (Error#1)
  ─

  4 tests passed
  1 test todo
Done in 7.28s.
```

who knows what version of the SDK `agoric install` is linking to.
